# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost

development:
  <<: *default
  database: avtomat_kalashnikova_development

test:
  <<: *default
  database: avtomat_kalashnikova_test

production:
  <<: *default
  database: avtomat_kalashnikova_production
  